[package]
name = "pointcloud"
version = "0.1.1"
edition = "2018"

description = "An accessor layer for grandma"
readme = "README.md"

authors = ["Sven Cattell <scattell@gmail.com>"]

documentation = "https://docs.rs/pointcloud"
homepage = "https://github.com/elastic/grandma"
repository = "https://github.com/elastic/grandma.git"

license-file = "../LICENSE.txt"

keywords = ["datasets"]
categories = ["science", "data-structures"]

[dependencies]
csv = "1"
libc = "0.2"
yaml-rust = "0.4"
rayon = "1.3"
packed_simd = "0.3.3"
glob = "0.2.11"
indexmap = {version = "1.0.2", features = ["serde-1"]}
serde_json = "1.0.48"
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"

[dev-dependencies]
tempdir = "0.3"
assert_approx_eq = "1.0.0"
