[package]
name = "pointcloud"
version = "0.3.0"
edition = "2018"

description = "An accessor layer for grandma"
readme = "README.md"

authors = ["Sven Cattell <scattell@gmail.com>"]

documentation = "https://docs.rs/pointcloud"
homepage = "https://github.com/elastic/grandma"
repository = "https://github.com/elastic/grandma.git"

license-file = "../LICENSE.txt"

keywords = ["datasets"]
categories = ["science", "data-structures"]

[badges]
travis-ci = { repository = "https://github.com/elastic/grandma.git", branch = "master" }

[toolchain]
channel = "nightly"

[dependencies]
csv = "1"
libc = "0.2.71"
yaml-rust = "0.4"
rayon = "1.3.1"
packed_simd = "0.3.3"
glob = "0.3.0"
fxhash = "0.2.1"
hashbrown = { version = "0.8", features = ["rayon"] }
serde_json = "1.0.55"
serde = { version = "1.0.114", features = ["derive"] }
flate2 = "1.0"
rand = "0.7.3"
smallvec = "1.3.0"

[dev-dependencies]
tempdir = "0.3"
assert_approx_eq = "1.0.0"
