[package]
name = "goko"
version = "0.3.7"
edition = "2018"

description = "A lock-free, eventually consistent, concurrent covertree."
readme = "README.md"

authors = ["Sven Cattell <scattell@gmail.com>"]

documentation = "https://docs.rs/goko"
homepage = "https://github.com/elastic/goko"
repository = "https://github.com/elastic/goko.git"

keywords = ["cover-tree","knn","lock-free"]
categories = ["concurrency", "data-structures"]

license-file = "../LICENSE.txt"
include = ["protos/tree_file_format.proto","build.rs","src/*","Cargo.toml"]

[toolchain]
channel = "nightly"

[features]
docs-only = []


[lib]
path = "src/lib.rs"
test = true

[dependencies]
protobuf = "2.16.2"
rand = "0.7.3"
yaml-rust = "0.4.4"
pbr = "1.0.3"
fxhash = "0.2.1"
rayon = "1.3.1"
hashbrown = { version = "0.8", features = ["rayon"] }
crossbeam-channel = "0.4.2"
pointcloud = { version = "0.3.5", path = "../pointcloud" }
#evmap = { git = "https://github.com/comath/rust-evmap" }
smallvec = "1.4.1"
type-map = "0.3.0"
statrs = "0.13.0"

[dev-dependencies]
assert_approx_eq = "1.0.0"

[build-dependencies]
protoc-rust = "2.16.2"

[package.metadata.docs.rs]
features = [ "docs-only" ]